### ISSUE TITLE
What happened to Zion?

### ISSUE THREAD

**Issue by jedisct1** [zionlang/vim-zion#1]
Hi,

Looks like the Zion repository vanished. What happened? Is Zion something you are still working on?

**Comment by wbbradley** [comment]
Hey Frank, thanks for asking. I've just taken a new job, and I need to work
through any potential implications of having an open source project while
being employed before I bring it back into public availability. I know that
my employer is generally favorable towards this sort of thing, but for my
own sake, I'm doing some due diligence.

I noticed that you had added Zion to the libsodium docs regarding languages
that had bindings for that library. That was great to see. I had gotten
Zion v1 to a state of relative stability (for a single person open source
compiler project). But, then began work on Zion v2 in December. Perhaps I
will put Zion v1 back out there so that folks can learn from it.

Cheers,
Will

**Comment by jedisct1** [comment]
Hi Will!

Thanks for the update, and congrats for your new gig and for Zion v2!

Yes, maybe putting back Zion v1 back online along with a teaser about the rewrite wouldn't be a bad idea :)

Cheers!

-Frank.
